### ISSUE TITLE
No access to azure pipeline builds

### ISSUE THREAD

**Issue by halfnibble** [compnerd/swift-win32#11]
The docs mention using the nightly builds of Swift, but I don't think those are publicly available to download via your azure link.

**Comment by compnerd** [comment]
They are publicly available, however, the links are no longer valid.  I've been reworking all the builds on Azure to scale better and to add new configurations.  I'll update the links once everything is working.

**Comment by cup** [comment]
https://github.com/compnerd/swift-win32/issues/12

**Comment by compnerd** [comment]
BTW, there is a recent build now at https://compnerd.visualstudio.com/swift-build/_build/results?buildId=22989&view=results. There is more shuffling that I am working on to add additional build configurations.  That link should remain valid for a while though and by then hopefully the builds will have stabilized.  Sorry about that.
