### ISSUE TITLE
.exe

### ISSUE THREAD

**Issue by ddanilyuk** [compnerd/swift-win32#175]
Hello, is it possible now to make an exe file that will store all the necessary libraries in itself?
And what is the likelihood that the builded swift-application will run on old builds of Windows 10?

Thank you.

**Comment by compnerd** [comment]
You cannot store libraries in an executable.  Do you mean is it possible to bundle the DLLs with exe?  If so, yes, you can create a bundle with the necessary DLLs.

As to the older versions of Windows, anything before 10.0.17763 is unsupported as the standard library actually uses APIs introduced in the release.
