### ISSUE TITLE
No UICatalog.exe

### ISSUE THREAD

**Issue by svanimpe** [compnerd/swift-win32#249]
When I build the UICatalog with `swift build -Xswiftc -use-ld=lld --target UICatalog`, there is no `UICatalog.exe` anywhere in the `.build` directory.

I don't see any errors during the compilation process. There's just no executable to be found.

**Comment by compnerd** [comment]
Ah, I think that this is a documentation issue - the target builds the objects, not the actual executable.  I need to figure out the correct command to build that.  A PR to improve the documentation is certainly welcome :)

**Comment by svanimpe** [comment]
This works for me:

`swift build -Xswiftc -use-ld=lld --product UICatalog`

It also works without the flags:

`swift build --product UICatalog`

Should it?

In both cases, I get a working **.exe**. However, the UI elements look a bit older than those in your screenshot.

**Comment by compnerd** [comment]
Ah, right, that change makes perfect sense.

You're correct about not needing the -Xswiftc -use-ld=lld as that now is implicit with SPM (at least as of the 10/27 snapshot).

The widgets looking old is expected if you did not manually copy the files to the correct location after building.  That's currently a limitation of SPM that I'm not sure how to mitigate.

A PR to update the instructions would be wonderful 😄

**Comment by svanimpe** [comment]
Just the one-liner?

And is CMake still the recommended method, or can that be removed as well?

**Comment by compnerd** [comment]
Yeah, the one liner :)

The CMake is still the recommended way until we can figure out the additional file copying step.
