### ISSUE TITLE
Could not download the nightly build from Azure?

### ISSUE THREAD

**Issue by Guang1234567** [compnerd/swift-win32#310]
Hello dev:

I just want to build this project with `swift-build`, but the toolchain download from the `swift.org` that not support `swift-build`.

So i want to download the toolchain from Azue to try it again, but can not download.  Thanks.

**Comment by Guang1234567** [comment]
In addition, 
[swift-DEVELOPMENT-SNAPSHOT-2020-12-01-a-windows10.exe](https://swift.org/builds/development/windows10/swift-DEVELOPMENT-SNAPSHOT-2020-12-01-a/swift-DEVELOPMENT-SNAPSHOT-2020-12-01-a-windows10.exe) download from `swift.org` also not working.

![Uploading 1607409057204.jpg…]()

**Comment by compnerd** [comment]
Yes, the 12/01 snapshot is known to have issues with SPM.

You should be able to grab the latest snapshot from Azure though if you like (e.g. https://dev.azure.com/compnerd/swift-build/_build/results?buildId=44103&view=artifacts&pathAsName=false&type=publishedArtifacts)

**Comment by Guang1234567** [comment]
> https://dev.azure.com/compnerd/swift-build/_build/results?buildId=44103&view=artifacts&pathAsName=false&type=publishedArtifacts

@compnerd 

Thank you very much !
