### ISSUE TITLE
[SPM] TSCUtility/Triple.swift:152: Fatal error: could not determine host triple: malforme

### ISSUE THREAD

**Issue by Guang1234567** [compnerd/swift-win32#327]
Hello dev:

```bash

c:\Users\User\Downloads\swift-win32>swift build

TSCUtility/Triple.swift:152: Fatal error: could not determine host triple: malformed

error: unable to invoke subcommand: C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swift-build.exe ()
```

But sometimes get works, -_-||

The solution maybe metioned on :
https://github.com/google/swift-jupyter/issues/103#issuecomment-619130911

Thanks.

**Comment by compnerd** [comment]
What version of the toolchain are you using?

**Comment by Guang1234567** [comment]
[12/01 snapshot](https://dev.azure.com/compnerd/swift-build/_build/results?buildId=44103&view=artifacts&pathAsName=false&type=publishedArtifacts)

**Comment by Guang1234567** [comment]
![Uploading image.png…]()

**Comment by Guang1234567** [comment]
![image](https://user-images.githubusercontent.com/8240718/102181655-fa239180-3ee5-11eb-9a5d-a396b18f45a9.png)

**Comment by compnerd** [comment]
The 12/01 snapshot did not have a working SPM.  You should use 11/18 or so which the GH Actions based CI is using.  This is not a Swift/Win32 issue.

**Comment by compnerd** [comment]
As of today, the snapshot that the github actions workflow is using is the 12/12 snapshot.  I recommend that if you are using snapshots, you follow the version that the GItHub Actions workflow uses (see .github/workflows/windows.yml).

**Comment by Guang1234567** [comment]
12/12 snapshot has the same issue:

```bash
  ~\downloads\Swift_Boost_Context   master ≣                                 User@WINDEV2011EVAL  22:08:20 
❯ swift build -v
C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swiftc.exe -print-target-info
C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swiftc.exe -print-target-info
C:\Users\User\downloads\Swift_Boost_Context: error: manifest parse error(s):
lld-link: error: <root>: undefined symbol: mainCRTStartup
lld-link: error: undefined symbol: memcpy
>>> referenced by C:\Users\User\AppData\Local\Temp\Package-82fa01.o:(main)
>>> referenced by C:\Users\User\AppData\Local\Temp\Package-82fa01.o:(main)
>>> referenced by C:\Users\User\AppData\Local\Temp\Package-82fa01.o:(main)
>>> referenced 9 more times
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

**Comment by compnerd** [comment]
You are not running it from the x64 Developer Command Prompt AFAICT.  Are you sure that you used the *DEVELOPER* command prompt?  The startup of the shell will execute parts of Visual Studio's setup that are required to get the environment correct.

**Comment by Guang1234567** [comment]
> You are not running it from the x64 Developer Command Prompt AFAICT. Are you sure that you used the _DEVELOPER_ command prompt? The startup of the shell will execute parts of Visual Studio's setup that are required to get the environment correct.

Aslo try "x64 Developer Command Prompt"  as below screen snapshot, thanks.

https://github.com/compnerd/swift-win32/issues/327#issuecomment-745095855

**Comment by compnerd** [comment]
I happened to come across this on GitHub actions once.  I think that this is a bug in SPM, and is transient.  Re-running the command seemed to be fine on GitHub at least.  I think that reporting the issue on bugs.swift.org might be reasonable.
