### ISSUE TITLE
[Help] unable to invoke subcommand

### ISSUE THREAD

**Issue by JeromeK13** [compnerd/swift-win32#329]
After i installed i wanted to create my first package like this:

`swift package init --type=executable`
but i receive the following error. I installed VS with all the needed dependencies.
Any ideas?
`error: unable to invoke subcommand: C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swift-package ()`

Greets Jerome

**Comment by compnerd** [comment]
This seems like a SPM issue, not a Swift/Win32 issue.  This is not the right place for help.  I suspect that you are using a snapshot that has issues (if you are using snapshots, I would highly recommend that you follow what the GitHub Actions workflow uses - you can see .github/workflows/windows.yml for the current version that is in use).  As of today that is the 12/12 snapshot.
