### ISSUE TITLE
UICatalog resources structure not populated by CMake build

### ISSUE THREAD

**Issue by deatondg** [compnerd/swift-win32#330]
I have just installed the latest Visual Studio, the latest versions of the required components, and the latest Swift for Windows. Following the build instructions for CMake
```
cmake -B build -D BUILD_SHARED_LIBS=YES -D CMAKE_BUILD_TYPE=Release -D CMAKE_Swift_FLAGS="-sdk %SDKROOT%" -G Ninja -S .
ninja -C build SwiftWin32 UICatalog
```
seems to build correctly, but running
```
%CD%\build\bin\UICatalog.exe
```
just prints 
```
Good morning!

```
and then exits.

However, building with 
```
swift build --product UICatalog
copy Examples\UICatalog\UICatalog.exe.manifest .build\x86_64-unknown-windows-msvc\debug\
copy Examples\UICatalog\Info.plist .build\x86_64-unknown-windows-msvc\debug\
```
succeeds, and then running
```
%CD%\.build\x86_64-unknown-windows-msvc\debug\UICatalog.exe
```
works as expected (although `swift run UICatalog` results in `error: Error Domain=NSCocoaErrorDomain Code=256 "(null)"`).

If I am missing some needed information, let me know and I will provide it.

**Comment by compnerd** [comment]
Ah, we are not creating the resource directory structure that is expected in CMake; that is an oversight on my part (mostly because I had created it locally).  Thanks for identifying this!
