### ISSUE TITLE
Views and Controls: support actions on `Label`

### ISSUE THREAD

**Issue by rjpilgrim** [compnerd/swift-win32#440]
Hello,

I have a need for clickable Labels in my application. I have pasted the implementation I added below to support this, but my need for this does sort of reveal a weakness in the extendibility of the Views in the library. Should there be a way to distinguish between a nonclickable and a clickable label? Specifically, I needed to add the SS_NOTIFY style to the Static Control to make it clickable, but since "style" is a type variable, there is no way to pass the style as a new parameter. As such, I am forced to create basically a new class to support a clickable Label which doesn't seem ideal. 

Is there some way to make the style property on Views parameterizable?

Clickable Label Implementation (additions stolen mostly from existing Button implementation):

```
import WinSDK

private let SwiftLabelProc: SUBCLASSPROC = { (hWnd, uMsg, wParam, lParam, uIdSubclass, dwRefData) in
  let button: ClickableLabel? = unsafeBitCast(dwRefData, to: AnyObject.self) as? ClickableLabel

  switch uMsg {
  case UINT(WM_LBUTTONUP):
    button?.sendActions(for: .primaryActionTriggered)
  default:
    break
  }

  return DefSubclassProc(hWnd, uMsg, wParam, lParam)
}

public class ClickableLabel: Control {
  private static let `class`: WindowClass = WindowClass(named: WC_STATIC)
  private static let style: WindowStyle = (base: WS_TABSTOP | DWORD(SS_NOTIFY), extended: 0)

  public override var font: Font! {
    get { return super.font }
    set(value) { super.font = value }
  }

  @_Win32WindowText
  public var text: String?

  public init(frame: Rect) {
    super.init(frame: frame, class: ClickableLabel.class, style: ClickableLabel.style)
    _ = SetWindowSubclass(hWnd, SwiftLabelProc, UINT_PTR(1),
    /                     unsafeBitCast(self as AnyObject, to: DWORD_PTR.self))
  }

  // ContentSizeCategoryAdjusting
  public var adjustsFontForContentSizeCategory = false

  // TraitEnvironment
  override public func traitCollectionDidChange(_ previousTraitCollection: TraitCollection?) {
    super.traitCollectionDidChange(previousTraitCollection)
    guard self.adjustsFontForContentSizeCategory else { return }
    self.font = FontMetrics.default.scaledFont(for: self.font,
                                               compatibleWith: traitCollection)
  }
}

extension ClickableLabel: ContentSizeCategoryAdjusting {
}
```

**Comment by compnerd** [comment]
This really shouldn't be something which someone should need to do, that is, this is something which `Label` should support out of the box.  The `Label` should default to `SS_NOTIFY`, with `STN_CLICKED` actually being dispatched as in `Button` - `sendActions(for: )`.  This isn't implemented yet, but something that I would gladly accept a patch for.
