### ISSUE TITLE
Issue when ninja building UICatalog

### ISSUE THREAD

**Issue by Hxsyed** [compnerd/swift-win32#628]
Hello there @compnerd, I have successfully run the cmake command, but when I try to run the ninja build command I am getting errors. Any idea why? 

![4](https://user-images.githubusercontent.com/63178444/124334506-4920d380-db65-11eb-83fd-77274c8ea2b4.PNG)

![2](https://user-images.githubusercontent.com/63178444/124334485-2ee6f580-db65-11eb-8a41-ae87a23e93f4.PNG)

![3](https://user-images.githubusercontent.com/63178444/124334486-30182280-db65-11eb-8223-fce9e4387077.PNG)

**Comment by compnerd** [comment]
Please provide textual output, screenshots are not a convenient option for diagnosing build issues.

**Comment by Hxsyed** [comment]
[CMakeError.log](https://github.com/compnerd/swift-win32/files/6757450/CMakeError.log)
[CMakeOutput.log](https://github.com/compnerd/swift-win32/files/6757451/CMakeOutput.log)

**Comment by compnerd** [comment]
Thanks, the same to you as well :)

Could you provide the full output of the configure + build run as text please?  Preferably with `ninja -C out -v UICatalog`

**Comment by Hxsyed** [comment]
Hi @compnerd attached is the txt file. 

[errortxt.txt](https://github.com/compnerd/swift-win32/files/6769960/errortxt.txt)

**Comment by compnerd** [comment]
Okay, the full logs are pretty helpful here.  The build is using Swift 5.4.1:
```
-- The Swift compiler identification is Apple 5.4.1
```
I'm not currently testing anything except main for the CMake builds in CI and didn't realize that I had broken that.  The linker errors are a failure to locate the symbols from Logging.  However, you would find that Logging is being built:
```
[2/5] cmd.exe /C "cd . && C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swiftc.exe -output-file-map Sources\CMakeFiles\Logging.dir\Release\output-file-map.json -incremental -j 16 -emit-library -static -o lib\Logging.lib -module-name Logging -module-link-name Logging -emit-module -emit-module-path swift\Logging.swiftmodule -emit-dependencies  -O -libc MD  ..\Packages\swift-log\Sources\Logging\Locks.swift ..\Packages\swift-log\Sources\Logging\LogHandler.swift ..\Packages\swift-log\Sources\Logging\Logging.swift    && cd ."
```
Logging is being built statically, which is not actually supported although I've added some experimental support on main for that.  You could use the latest snapshots from main, alternatively, changing the `STATIC` to `SHARED` at https://github.com/compnerd/swift-win32/blob/main/Sources/CMakeLists.txt#L34 should also work.  I suppose that it makes sense to adjust that using a condition based on the compiler version.

**Comment by Hxsyed** [comment]
Hello @compnerd I have tried to replace the lines of code in my CMakeList.txt file but i am still running into errors. 

![image](https://user-images.githubusercontent.com/63178444/124760646-f184be00-defe-11eb-89b0-03be9fd1067f.png)

CmakeList file - [CMakeLists.txt](https://github.com/compnerd/swift-win32/files/6777187/CMakeLists.txt)

**Comment by compnerd** [comment]
Could you try with the latest version of the repository?  I _think_ it should be resolved.

**Comment by Hxsyed** [comment]
Thank you so much it works
