### ISSUE TITLE
Window doesn't Open

### ISSUE THREAD

**Issue by ABINASH-KUMAR-ctrl** [compnerd/swift-win32#709]
After compilation of `UICatalog`  no windows opens but in the console it just prints this
```cmd
2022-05-30T12:32:19+0530 error org.compnerd.swift-win32 : [SwiftWin32] InitCommo
nControlsEx: Win32 Error 0 - The operation completed successfully.
```

**Comment by compnerd** [comment]
How are you building?  Did you build with CMake?

**Comment by ABINASH-KUMAR-ctrl** [comment]
Yes using Clion with Swift plugin installed

**Comment by compnerd** [comment]
Hmm, odd, that should deploy the full set of files.  Can you share the output of `ninja -t commands UICatalog` in a gist?

**Comment by ABINASH-KUMAR-ctrl** [comment]
Accidentally i ruined the whole installation then reinstalled everything now it working fine
