### ISSUE TITLE
error: cannot find type 'BarButtonItem' in scope; examples don't compile

### ISSUE THREAD

**Issue by Ilyab99** [compnerd/swift-win32#747]
`C:\Users\Ilya Bagleybter\Desktop\swift-win32\Sources\SwiftWin32\View Controllers\ViewController.swift:1151:46: error: cannot find type 'BarButtonItem' in scope
  open func setToolbarItems(_ toolbarItems: [BarButtonItem]?, animated: Bool) {
                                             ^~~~~~~~~~~~~
error: fatalError
ninja: build stopped: subcommand failed.
`

since it doesn't appear to be implemented removing any mentions of ViewController.swift fixes it

**Comment by compnerd** [comment]
How are you building?  I think I might’ve failed to update the CMakeLists.txt as the CI didn’t error out.

**Comment by nmilev-scribe** [comment]
I am experiencing the same issue. Trying to build from Visual Studio 2022 by simply selecting build all.

**Comment by compnerd** [comment]
Okay, so building via CMake.  Thank you, let me see if I can reproduce the issue.

**Comment by compnerd** [comment]
@nmilev-scribe would you happen to be able to try with the SPM instructions?  I suspect that they are more robust due to the CI building with SPM only atm.
