### ISSUE TITLE
Example of SwiftWin32UI App

### ISSUE THREAD

**Issue by WillyAguilera1977** [compnerd/swift-win32#774]
Please could you give me a simple example of SwiftWin32UI App

**Comment by compnerd** [comment]
Unfortunately, SwiftWin32UI is not fleshed out enough to be able to generate a complete application.  The underlying implementation of SwiftWin32 should give you enough of the controls to implement an application.  Patches to flesh out a SwiftUI like model on top of SwiftWin32 are absolutely welcome!
