### ISSUE TITLE
Building fails with an internal error: symlinks not supported

### ISSUE THREAD

**Issue by libewa** [compnerd/swift-win32#781]
When trying to build or resolve package, the process exits with this error:
```shell
E:\swift\happyworkwin> swift package resolve
Updating https://github.com/compnerd/swift-win32.git
Updated https://github.com/compnerd/swift-win32.git (0.78s)
error: the package manifest at '\Package@swift-5.8.swift' cannot be accessed (InternalError(description: "Internal error. Please file a bug at https://github.com/apple/swift-package-manager/issues with this info. symlinks not supported")) in https://github.com/compnerd/swift-win32.git
E:\swift\happyworkwin>
```
As the error message says, this is probably due to `Package@swift-5.8.swift` just being a symlink to `Package@swift-5.7.swift`. This seems like it's not needed, as I use Swift 5.9.2 which automatically failed back to the (broken) 5.8 `Package.swift`.

**Comment by compnerd** [comment]
This is a user configuration issue - you need to enable symbolic links on your host. SPM already uses symbolic links and requires that they be enabled, so using them here is not really an additional step.
