### ISSUE TITLE
Missing .plist file causes the Application not showing

### ISSUE THREAD

**Issue by felixf4xu** [compnerd/swift-win32#787]
Hi,

I managed to compile the project and generate `UICatalog.exe`, but when I double click it to run, no GUI is displayed, only a console window with this message:
>error org.compnerd.swift-win32 : [SwiftWin32] InitCommonControlsEx: Win32 Error 0 - The operation completed successfully.

I tried to debug step-by-step using vscode, this is the code stopped at last:

```swift
    _ = MsgWaitForMultipleObjects(0, nil, false,
                                  DWORD(exactly: time?.timeIntervalSinceNow ?? -1)
                                      ?? INFINITE,
                                  QS_ALLINPUT | DWORD(QS_KEY) | QS_MOUSE | DWORD(QS_RAWINPUT))
```
I mean I can set a breakpoint at `MsgWaitForMultipleObjects` and the breakpoint stops, if I continue to run, it runs, but nothing happens from there.

Win11, 23H2, 22631.4317, Visual Studio 2022 installed
swift 6.0.2
main branch of this repo.

**Comment by felixf4xu** [comment]
> swift 6.0.2

oh, I guess I'm still compiling using swift 5.9 mode, because I set `// swift-tools-version:5.9`. It will not compile if I set it to 6.0

**Comment by felixf4xu** [comment]
After I read the README again, I fount out that I need to run:
```sh
mt -nologo -manifest Examples\UICatalog\UICatalog.exe.manifest -outputresource:.build\x86_64-unknown-windows-msvc\debug\UICatalog.exe
copy Examples\UICatalog\Info.plist .build\x86_64-unknown-windows-msvc\debug\
.build\x86_64-unknown-windows-msvc\debug\UICatalog.exe
```
Now it worked.

**Comment by felixf4xu** [comment]
I found that the menifest tool only makes the GUI display nicer (I tested by purposely skip the `mt` step), it's actually the .plist file that prevent the exe to show up.

**Comment by compnerd** [comment]
Yes, the plist is required, that is not a bug but expected behaviour. There is no way to know the default type names and it needs to be provided by the developer.

**Comment by felixf4xu** [comment]
In that case, `Info.plist` should be **Required**, the document like followings might not be accurate:

>| Info.plist | **(Optional)** The *information property list* file is a structured file that contains configuration information for the application. |
 
>| Info.plist | (Recommended) The file contains confituration information for the application. |
